# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c78aa77fc7543fb0d9c3185684e18475185385416a2afac913e2285e5a69f00575a822ff6c0cb46c08994927a045034d11bed55193923dc6b43e020dd6ecd25

test:
  secret_key_base: 85301c3c802091170a09c294bd46f76af5070773b217a405dae7945d9c4623593451cff205ba6fd945eab2de34a876cd4af1758eb833df40d4e89a564272afe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
